### ISSUE TITLE
[Enhancement] Custom Description field for preset awards

### ISSUE THREAD

**Issue by weepingminotaur** [jsavko/pf2e-award-xp#16]
Even when adding, for example, a moderate or severe award after an encounter, you might still want to enter some descriptive text.

**Comment by jsavko** [comment]
Then use the custom description field

**Comment by weepingminotaur** [comment]
OK. That's one extra step -- selecting custom, adding XP value manually, then text description -- but you clearly don't think it's worthwhile, so that's that. No offence meant.

**Comment by weepingminotaur** [comment]
I really like the elegance of this module.
