### ISSUE TITLE
Errors while awarding XP while non-"character" type actor is in party

### ISSUE THREAD

**Issue by Sevaarcen** [jsavko/pf2e-award-xp#4]
I've been loving this module so far, it's made it a lot easier to handle XP in my game. My players and I have spotted an issue that can lead to errors while awarding XP depending on what actor types are in the party.

When Awarding XP outside of combat, non-player character actors (e.g. Familiars) might be in the "party", but they are not valid targets to be awarded XP. Right now, these invalid targets are included by default when using a default award XP dialog (e.g. `game.pf2e_awardxp.openDialog()`).

If the GM leaves these invalid targets checked in the XP award dialogue and presses the "Award" button, the following will happen:
1. Each party member prior to the first invalid target will receive XP
2. Attempting to give XP to an invalid target will produce the following error (visible in the browser developer console): `TypeError: destination.system.details.xp is undefined`
3. All remaining party members will receive no XP
4. The dialog window remains open, no errors are displayed in Foundry to the GM, and no message is posted in the chat saying that any XP was awarded. If the GM doesn't realize there is an error, and presses the "Award XP" button again, this will result in the steps above repeating.

One straightforward fix is to filter out any non-"character" actor types from the party in the default XP dialog (see my related PR https://github.com/jsavko/pf2e-award-xp/pull/5)

**Comment by Sevaarcen** [comment]
In addition to the 1 line changed in the PR, I had some other ideas to help protect against improperly awarding XP (either due to a JS/browser/network issue, or accidental double-clicks of the Award button (which can award XP twice).

1. JS Console logging of XP being awarded, the character's previous XP, the amount being awarded, and the new XP total. If an issue occurs, this could aid in debugging or reverting the XP changes.
2. Disabling the dialog as the first action when pressing "Award". This would decrease the time that the dialog would remain active, decreasing the time window where a double-click could possibly trigger awarding XP twice.
3. Including a nonce for the award dialog and ensuring that a player character isn't awarded XP twice even if a double-click event occurred

I can document this up in a separate, related issue if you wish as well.

Thank you!

**Comment by jsavko** [comment]
Disabling the submit button is something I had planned for the next update.  I also like the logging and will implement that as well. 

Thank you for your suggestions
