### ISSUE TITLE
Exclude neutral or party alliance from XP calculation

### ISSUE THREAD

**Issue by mechamaya** [jsavko/pf2e-award-xp#9]
Would it be possible to exclude neutral or party allied NPCs from XP calculation? Currently no matter their allegiance these NPCs are calculated in the XP total, even if they are just a civilian that needs to be protected or what have you. I don't think this needs to alter the party size necessarily, as that would drastically change the XP calculations, but mostly just would be nice to not treat these NPCs as enemies.

**Comment by jsavko** [comment]
Does the core xp calculation on the encounter tab filter them? I am using the core pf2e function for calculating that xp award

**Comment by mechamaya** [comment]
I've noticed the core xp calculation does exclude them, but when the xp is awarded after the encounter is ended, it includes it. I had a 100xp encounter with 2 helpful NPCs and 4 enemies, but when i ended the encounter, the dialog defaulted to 200 xp.

**Comment by jsavko** [comment]
I don't see a way to flag the npc as helpful on the combat tracker. You may be using a module that adds that functionality

**Comment by mechamaya** [comment]
![image](https://github.com/jsavko/pf2e-award-xp/assets/24398689/2743a9d4-700a-42fc-a066-fc44ec830bd5)
![image](https://github.com/jsavko/pf2e-award-xp/assets/24398689/e2a8abb5-0169-4117-abb8-cf50575bfe11)
In the character or monster page there is a configure button that sets the Alliance. This is without any modules enabled

**Comment by jsavko** [comment]
Ah I was unaware of that menu. Thanks for the information.  Next release will only calculate opposition for xp values
